// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl0khGIkY0y0Jf-xsfHEm3ld-Io2RhjDA',
    appId: '1:549279616411:web:7ca7e7839b4189199c253e',
    messagingSenderId: '549279616411',
    projectId: 'flutter-study-app-3ac6c',
    authDomain: 'flutter-study-app-3ac6c.firebaseapp.com',
    storageBucket: 'flutter-study-app-3ac6c.appspot.com',
    measurementId: 'G-0RDTBGZ7J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPk58CBotYI5kc1QGDhOGlCqW9-QFQcto',
    appId: '1:549279616411:android:43f3e81e7743bbbd9c253e',
    messagingSenderId: '549279616411',
    projectId: 'flutter-study-app-3ac6c',
    storageBucket: 'flutter-study-app-3ac6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPipgns5hW9WyQBkaSBRmQyzLfxxriMsk',
    appId: '1:549279616411:ios:0b8ff4e67660d0ae9c253e',
    messagingSenderId: '549279616411',
    projectId: 'flutter-study-app-3ac6c',
    storageBucket: 'flutter-study-app-3ac6c.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPipgns5hW9WyQBkaSBRmQyzLfxxriMsk',
    appId: '1:549279616411:ios:943e8246af07fd469c253e',
    messagingSenderId: '549279616411',
    projectId: 'flutter-study-app-3ac6c',
    storageBucket: 'flutter-study-app-3ac6c.appspot.com',
    iosBundleId: 'com.example.flutterStudyApp.RunnerTests',
  );
}
